apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-rcwxyfpl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-rcwxyfpl 
  name: go-rcwxyfpl
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-rcwxyfpl
    weight: 100 
